### ISSUE TITLE
Project Checkpoint 1 - Instructor Notes

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [erbecerra/HappyHabits#1]
What a fun and useful project idea!  I like the Poke integration too - nice find!  Your user story list seems to document a well-defined MVP that should be very doable in the semester timeframe.  Screens are looking good - I think these will serve you well as you begin building out your jsps. 

Just a few questions/comments:

- [x] There is a line in the problem statement that should probably be removed because your project is the real thing: "This repository will serve as an example for Madison College's Enterprise Java Class."
- [x] Is there any need to have a delete user story? 
- [x] The readme.md refers to an admin role, but I don't see any user stories for an admin user?
- [x] timeLog.md - some of the markdown isn't rendering very well in GitHub - I think adding a space after the hashes should resolve it. 
- [x] The Project Plan and Screen Design links at the bottom of the readme.md don't link correctly.
- [x] You mentioned the DB design as an open item in your timelog/reflection. Is everything represented on the screens that you'll need in your database?
- [x] Missing project plan?

**Comment by erbecerra** [comment]
All the links, unneeded text, formatting are now updated. I do have the project plan there the link is now working. I don't have my database set up yet so that will be fleshed out more next week once I get there.

**Comment by pawaitemadisoncollege** [comment]
Looks good!
